# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19f0c569e9861d378e6e8b81ff124b4663e9e221f17d2ab1d68182975520f4639ed6117b59257f165552c8847f9c27b7259c669a4757894322b82f6edbdb9b8

test:
  secret_key_base: 6b2b14460849219f0fe59b527373e59229c6dc984c420244b07d8a36771f7f821a9be6a3a16fe082ad774e9e9bcf009a3568908a463fa6ade128d89cc4096152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
